package com.fiveelements.calendar.admin;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fiveelements.calendar.admin.service.AdminService;
import com.fiveelements.calendar.security.JwtService;
import javax.sql.DataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

@JdbcTest(properties = "spring.flyway.enabled=false")
class AdminServiceTest {
  @Autowired DataSource dataSource;
  private JdbcTemplate template;
  private AdminService service;

  @BeforeEach
  void setUp() {
    template = new JdbcTemplate(dataSource);
    template.execute(
        "CREATE TABLE IF NOT EXISTS sys_admin_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY"
            + " PRIMARY KEY, username VARCHAR(64) UNIQUE, password VARCHAR(255), display_name"
            + " VARCHAR(64), status CHAR(1) DEFAULT '0', failed_login_attempts INT DEFAULT 0,"
            + " locked_until TIMESTAMP NULL, password_changed_at TIMESTAMP NULL, last_login_time"
            + " TIMESTAMP NULL)");
    template.execute(
        "CREATE TABLE IF NOT EXISTS sys_role (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY"
            + " KEY, role_code VARCHAR(64), role_name VARCHAR(64), status CHAR(1) DEFAULT '0')");
    template.execute(
        "CREATE TABLE IF NOT EXISTS sys_admin_user_role (admin_user_id BIGINT, role_id BIGINT)");
    template.execute(
        "CREATE TABLE IF NOT EXISTS sys_permission (id BIGINT GENERATED BY DEFAULT AS IDENTITY"
            + " PRIMARY KEY, permission_code VARCHAR(96), permission_name VARCHAR(96))");
    template.execute(
        "CREATE TABLE IF NOT EXISTS sys_role_permission (role_id BIGINT, permission_id BIGINT)");
    template.execute(
        "CREATE TABLE IF NOT EXISTS admin_login_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY"
            + " PRIMARY KEY, admin_user_id BIGINT NULL, username VARCHAR(64), ip_address"
            + " VARCHAR(64), success_flag CHAR(1), failure_reason VARCHAR(128), login_time"
            + " TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
    template.execute(
        "CREATE TABLE IF NOT EXISTS admin_operation_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY"
            + " PRIMARY KEY, admin_user_id BIGINT, operation_code VARCHAR(64), object_type"
            + " VARCHAR(32), object_id VARCHAR(64), ip_address VARCHAR(64), success_flag CHAR(1)"
            + " DEFAULT '1', operation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
    template.update("DELETE FROM admin_operation_log");
    template.update("DELETE FROM admin_login_log");
    template.update("DELETE FROM sys_admin_user_role");
    template.update("DELETE FROM sys_role_permission");
    template.update("DELETE FROM sys_permission");
    template.update("DELETE FROM sys_admin_user");
    template.update("DELETE FROM sys_role");
    template.update(
        "INSERT INTO sys_role(id,role_code,role_name) VALUES (1,'SUPER_ADMIN','Super"
            + " administrator')");
    template.update(
        "INSERT INTO sys_permission(id,permission_code,permission_name) VALUES"
            + " (1,'dashboard:view','View dashboard')");
    template.update("INSERT INTO sys_role_permission(role_id,permission_id) VALUES (1,1)");
    var encoder = new BCryptPasswordEncoder();
    template.update(
        "INSERT INTO sys_admin_user(id,username,password,display_name,status) VALUES"
            + " (1,'admin',?,'Admin','0')",
        encoder.encode("Original@123"));
    template.update("INSERT INTO sys_admin_user_role(admin_user_id,role_id) VALUES (1,1)");
    service =
        new AdminService(
            JdbcClient.create(dataSource),
            encoder,
            new JwtService("test-secret-that-is-at-least-32-bytes-long", 120),
            "admin",
            "",
            5,
            30);
  }

  @Test
  void locksAccountAfterConfiguredFailedAttemptsAndAuditsFailures() {
    for (int i = 0; i < 5; i++) {
      assertThatThrownBy(() -> service.login("admin", "wrong", "127.0.0.1"))
          .isInstanceOf(BadCredentialsException.class);
    }
    assertThat(
            template.queryForObject(
                "SELECT failed_login_attempts FROM sys_admin_user WHERE id=1", Integer.class))
        .isEqualTo(5);
    assertThat(
            template.queryForObject(
                "SELECT locked_until IS NOT NULL FROM sys_admin_user WHERE id=1", Boolean.class))
        .isTrue();
    assertThat(
            template.queryForObject(
                "SELECT COUNT(*) FROM admin_login_log WHERE success_flag='0'", Integer.class))
        .isEqualTo(5);
    assertThatThrownBy(() -> service.login("admin", "Original@123", "127.0.0.1"))
        .isInstanceOf(BadCredentialsException.class)
        .hasMessageContaining("locked");
  }

  @Test
  void successfulLoginClearsFailuresAndWritesAudit() {
    template.update("UPDATE sys_admin_user SET failed_login_attempts=2 WHERE id=1");
    AdminService.LoginResponse response = service.login("admin", "Original@123", "127.0.0.1");
    assertThat(response.accessToken()).isNotBlank();
    assertThat(
            template.queryForObject(
                "SELECT failed_login_attempts FROM sys_admin_user WHERE id=1", Integer.class))
        .isZero();
    assertThat(
            template.queryForObject(
                "SELECT COUNT(*) FROM admin_login_log WHERE success_flag='1'", Integer.class))
        .isEqualTo(1);
  }

  @Test
  void changesPasswordAndRejectsWeakPassword() {
    assertThatThrownBy(() -> service.changePassword(1, "Original@123", "short", "127.0.0.1"))
        .isInstanceOf(IllegalArgumentException.class);
    service.changePassword(1, "Original@123", "Replacement@123", "127.0.0.1");
    assertThat(service.login("admin", "Replacement@123", "127.0.0.1").accessToken()).isNotBlank();
    assertThat(
            template.queryForObject(
                "SELECT COUNT(*) FROM admin_operation_log WHERE"
                    + " operation_code='CHANGE_OWN_PASSWORD'",
                Integer.class))
        .isEqualTo(1);
  }

  @Test
  void preventsDisablingOrDemotingLastSuperAdministrator() {
    template.update("INSERT INTO sys_role(id,role_code,role_name) VALUES (2,'AUDITOR','Auditor')");
    assertThatThrownBy(
            () ->
                service.updateAdmin(
                    1,
                    1,
                    new AdminService.AdminAccountRequest("admin", "Admin", "", 1, false),
                    "127.0.0.1"))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessageContaining("own account");
    assertThatThrownBy(
            () ->
                service.updateAdmin(
                    2,
                    1,
                    new AdminService.AdminAccountRequest("admin", "Admin", "", 2, true),
                    "127.0.0.1"))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessageContaining("super administrator");
  }
}
