ALTER TABLE app_user
  ADD COLUMN gender CHAR(1) DEFAULT NULL COMMENT '0未知 1男 2女',
  ADD COLUMN birthday DATE DEFAULT NULL,
  ADD COLUMN region VARCHAR(128) DEFAULT NULL,
  ADD COLUMN signature VARCHAR(255) DEFAULT NULL;
