CREATE TABLE IF NOT EXISTS diary_tag (
 id BIGINT NOT NULL AUTO_INCREMENT,user_id BIGINT NOT NULL,tag_name VARCHAR(32) NOT NULL,use_count INT NOT NULL DEFAULT 0,create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uk_user_tag(user_id,tag_name)
) COMMENT='用户日记标签';
CREATE TABLE IF NOT EXISTS diary_tag_relation (
 id BIGINT NOT NULL AUTO_INCREMENT,diary_id BIGINT NOT NULL,tag_id BIGINT NOT NULL,
 PRIMARY KEY(id),UNIQUE KEY uk_diary_tag(diary_id,tag_id),KEY idx_diary(diary_id)
) COMMENT='日记标签关联';
CREATE TABLE IF NOT EXISTS user_reminder_setting (
 id BIGINT NOT NULL AUTO_INCREMENT,user_id BIGINT NOT NULL,reminder_type VARCHAR(32) NOT NULL,enabled CHAR(1) NOT NULL DEFAULT '1',remind_time TIME DEFAULT NULL,
 repeat_week VARCHAR(32) DEFAULT NULL,skip_if_completed CHAR(1) DEFAULT '1',reminder_text VARCHAR(128) DEFAULT NULL,
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uk_user_type(user_id,reminder_type)
) COMMENT='用户提醒设置';
